FROM docker.io/library/golang:1.24.2 as builder

USER root
ARG OSC_TOKEN

WORKDIR /usr/src/metrics-server
COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GO111MODULE=on
RUN go mod tidy
RUN go build -ldflags "-s -w" -a -o /usr/builded_application ./cmd/app/main.go

FROM scratch AS prod

ENV WORKDIR=/usr/src/app
WORKDIR $WORKDIR

COPY --from=builder /usr/builded_application ./metrics-server

CMD ["./server",]
